name: aula-pedidos-cache

services:
  postgres:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_DB: pedidos_cache
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pedidos_cache"]
      interval: 2s
      timeout: 3s
      retries: 20
    volumes:
      - pedidos_cache_postgres_data:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/001-init.sql:ro

  redis:
    image: redis:8.4-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 20

volumes:
  pedidos_cache_postgres_data:
